Repository intel/pmem-csi, pull requests merged in 2019-04, with the labels that each got.

#219 Change example deployment again
  README.md
  deploy/kubernetes-1.13/pmem-app-1.yaml
  deploy/kubernetes-1.13/pmem-app-2.yaml
  deploy/kubernetes-1.13/pmem-app.yaml
  deploy/kubernetes-1.13/pmem-storageclass.yaml
Labels: deployment, doc

#227 README: add verify labels step in "run in cluster" section
  README.md
Labels: doc

#222 deploy: use separate storage class yamls
  README.md
  deploy/kubernetes-1.13/pmem-app-1.yaml
  deploy/kubernetes-1.13/pmem-app-2.yaml
  deploy/kubernetes-1.13/pmem-app.yaml
  deploy/kubernetes-1.13/pmem-storageclass-ext4.yaml
  deploy/kubernetes-1.13/pmem-storageclass-xfs.yaml
  deploy/kubernetes-1.13/pmem-storageclass.yaml
  test/e2e/storage/csi_volumes.go
  test/start-stop.make
Labels: deployment, doc

#231 README: Move "Verify node labels" block after "Deploy driver" block
  README.md
Labels: doc

#243 Fix typo at README.md file.
  README.md
Labels: doc

#242 Modify pmem-CSI naming as specified internally.
  README.md
Labels: doc

#239 Deployment: add explicit /sys mount in pmem-ns-init in LVM mode
  deploy/kubernetes-1.13/pmem-csi-lvm.yaml
  deploy/kustomize/kubernetes-1.13-lvm/lvm-patch.yaml
Labels: deployment

#245 Change NamespaceCreation opts.Align to be 64-bit value
  pkg/ndctl/ndctl.go
  pkg/ndctl/region.go
  pkg/pmem-device-manager/pmd-ndctl.go
Labels: bug

#247 Modify pmem-CSI naming as specified internally.
  DEVELOPMENT.md
  README-qemu-notes.md
  deploy/kustomize/driver/README.md
  deploy/kustomize/testing/README.md
Labels: doc

#253 Fix kustomize-generated parts to be in sync again
  deploy/kubernetes-1.13/pmem-csi-lvm-testing.yaml
Labels: deployment

#240 better cluster filenames
  Makefile
  README.md
  test/clear-kvm.make
  test/setup-clear-kvm.sh
  test/start-stop.make
  test/start_qemu.sh
  test/test.make
Labels: testing

#248 Advance csi-node-driver-registrar version to 1.1.0
  deploy/kubernetes-1.13/pmem-csi-direct-testing.yaml
  deploy/kubernetes-1.13/pmem-csi-direct.yaml
  deploy/kubernetes-1.13/pmem-csi-lvm-testing.yaml
  deploy/kubernetes-1.13/pmem-csi-lvm.yaml
  deploy/kustomize/kubernetes-1.13/kustomization.yaml
Labels: deployment

#246 add args unit tests for pmem-ns-init, other minor unit testing improvements
  cmd/pmem-ns-init/main.go
  cmd/pmem-ns-init/main_test.go
  pkg/pmem-csi-driver/registryserver_test.go
  test/test.make
Labels: testing

#259 README: Add check "pvc state is Bound" in deployment steps
  README.md
Labels: doc
